-- Clasificación inicial de subcategoria por palabras clave del nombre.
-- Es una propuesta automática: lo que no encaja queda como 'Sin clasificar'
-- para revisión manual. Las etiquetas "(mover a servicios)" marcan filas que
-- hoy están cargadas como producto pero son procedimientos, estudios o
-- ítems administrativos; solo se etiquetan, no se mueven ni se borran.
-- Idempotente: solo pisa filas donde subcategoria sigue en null, así no
-- sobrescribe correcciones manuales hechas después.
update productos set subcategoria = case
 when categoria='Servicio' then 'Servicio'
 when rama is null then 'Sin clasificar'
 when rama='clinica' and categoria='Insumo clínico' and nombre ~* '(analisis|brucelosis|leishmania|\mt4\M|tsh|frotis|laboratorio general|serolog|pcr|elisa|citolog|histopatolog|hemograma|cultivo)' then 'Estudio de laboratorio (mover a servicios)'
 when rama='clinica' and categoria='Insumo clínico' and nombre ~* '(certificado|libreta|complejidad|medio control|mismo caso|consulta|internaci)' then 'Administrativo / honorarios (mover a servicios)'
 when rama='clinica' and categoria='Insumo clínico' and nombre ~* '(ectomi|ostomi|otomi|pexia|plastia|cirug|castraci|cesarea|hernia|carcinoma|mastectom|eventraci|desobstruc|perfil |limpieza|corte |extracci|extirpa|biopsia|ecograf|radiograf|eutanasia|amputaci|enucleaci|tratamiento|torsion|absceso|aplic|exceresis|fistula|fractura|neoplasia|tumor|ranula|ruptura|cuarto arco|\mpif\M|desparasitacion|quiste|prolapso|luxacion|lux\.|reseccion|drenaje|necropsia|sedaci|vendaje$|reduc|anestesia (general|inhal)|ductus|artrodesis|piometra|yeso|ablasion|trepanac|osteo|nodulo|otohemat|episio|reparacion|colocacion|ligament|cistitis|ovario|mamar|perianal|fisiot|laser|ozono|atresia|blefarorrafia|colgajo|cuerpo ext|ectropion|esofagostoma|fimosis|flap|higroma|hiperplasia|ocd|paladar|polipos|reintroduccion|restitucion|sialocele|sondeo|toracocentesis|vaciado)' then 'Procedimiento (mover a servicios)'
 when rama='clinica' and nombre ~* '(camiseta|collar isabelino|elastikan|faja|capita|protector post)' then 'Post-quirúrgico y protección'
 when rama='clinica' and nombre ~* '(vacuna|rabia|quintuple|sextuple|triple felina|octuple|moquillo|bordetella|virafel)' then 'Vacunas'
 when rama='clinica' and nombre ~* '(pipeta|spot|broadline|defender|frontline top)' then 'Antiparasitario - pipetas'
 when rama='clinica' and nombre ~* 'collar' then 'Antiparasitario - collares'
 when rama='clinica' and (categoria='Antiparasitario' or (nombre ~* '(nexgard|bravecto|simparica|cidar|\mgets\M|power gold|tandon|credelio|kil amitraz|hectopar|repexxin|tea 327|anti externo|terpan|frontline|amitraz|antiparasit|basken|cestodan|pulg|endofour|fenbendazol|fipronil|finox|ivermex|ivervet|ivomec|no aca|toltrazol|tolzuril|total full|repelente|a otra parte)' and nombre !~* '(shamp|locion|losion)')) then 'Antiparasitario - comprimidos, sprays y otros'
 when rama='clinica' and nombre ~* '(aurix|clean eyes|corulets|oftalmic|gotero|hialurina|ocufl|otipet|otovier|rosa de bengala|fluoresc|lagrima|oidos|colirio|tobramicina con dexa)' then 'Oftálmicos y óticos'
 when rama='clinica' and nombre ~* '(curabichera|crema|miconazol|pomada|pasta|atomiz|spray|lidoca|sulfadiazina|shamp|locion|losion|jabon|clorhex|tritohex|solucion jab|kuraderm|udder|balm|bactrovet|nitrofurazona|labyderm|derm caps|ade caps|filtro solar|espuma|spineda)' then 'Tópicos, curabicheras e higiene'
 when rama='clinica' and nombre ~* '(papel|toalla)' then 'Limpieza y papelería'
 when rama='clinica' and nombre ~* '(succinil|ketamina|propofol|xilacina|isofluor|anestesia|atropina|acepromacina|agua destilada|bicarbonato|suero|ringer|fisiologica|solucion|glucosa|cloruro|vaselina|alcohol|iodo|yodo|povidona|manitol|agua oxigenada|formol)' then 'Anestesia, soluciones y antisépticos'
 when rama='clinica' and nombre ~* '(adrenalina|eutanasico|heparina|hemospeed|eritropoyetina)' then 'Emergencia, eutanasia y hematología'
 when rama='clinica' and nombre ~* '(vincristina|azatioprina)' then 'Oncología e inmunosupresores'
 when rama='clinica' and nombre ~* '(bro k|fenobarbital|fluoxetina|dazam|diazep|clormadinona|caninsulin|oxitocina|metrergina)' then 'Neurología, comportamiento y hormonales'
 when rama='clinica' and (categoria='Medicamento' or nombre ~* 'estreptocarbo') and nombre ~* '(cilina|cef|doxiciclin|enroflox|enrroflox|ciproflox|clindamic|metronidazol|amoxi|azitromic|gentamic|sulfa|marbofl|tetraciclin|oxitetra|florfenicol|trimetoprim|itraconazol|ketoconazol|fluconazol|odontobiotic|pyo derm|dexaflox|tobramicin|floxadey|levoflox|enterosulf|tribiotic|estreptocarbo)' then 'Medicamento - antibióticos y antimicóticos'
 when rama='clinica' and categoria='Medicamento' and nombre ~* '(meloxicam|previcox|firocoxib|carprofeno|tramadol|pregabal|gabapal|gabalbech|gabapentina|dipirona|ketoprofeno|flunixin|cortidural|dexametasona|prednisolona|prednisona|metacam|onsior|robenacoxib|singestar|apoquel|novotioc|ocladerm)' then 'Medicamento - antiinflamatorios, analgésicos y antialérgicos'
 when rama='clinica' and categoria='Medicamento' and nombre ~* '(cardio|cardial|furosemida|enalapril|pimobendan|pimoden|semintra|artrin|artrosan|condroit|yohimbina)' then 'Medicamento - cardiología, renales y articulares'
 when rama='clinica' and categoria='Medicamento' and nombre ~* '(inyectable|ampolla|inyect|cerenia)' then 'Medicamento - inyectables varios'
 when rama='clinica' and nombre ~* '(kit cepillo|mamadera)' then 'Accesorios varios (clínica)'
 when rama='clinica' and categoria='Medicamento' and nombre ~* '(lactulosa|omeprazol|ranitidina|metoclopramida|ondansetron|probiotico|vitamina|suplemento|neovita|hepat|omega|gotas|jarabe|ferroglobin|inmunogam|enzimol|sustituto|calcio|hierro|tonico|nutripet|potenpet|alimento complementario|complejo vit|maternil|eutazum|paulferon|tioctic|cannabis|sucravet|cisticalm|urovier|ursomarina|ursoliv|proteliv|enterosep|enzimax|felilax|rehidratantes|nogastrol|rexilen|colotrin|koprofagia|bronco|neumoflogin)' then 'Medicamento - digestivos, urinarios, respiratorios y suplementos'
 when rama='clinica' and categoria='Medicamento' then 'Sin clasificar'
 when rama='clinica' and categoria='Insumo clínico' and nombre ~* '(bisturi|cuchilla|chuchilla|aguja|jeringa|gasa|venda|cinta|guante|cateter|abbocath|sonda|sutura|hilo|campo|barbijo|algod|tubo|recipiente|test|reactivo|tira|portaobjeto|lancet|bolsa agua|estetoscopio|termometro|llave de|microgotera|cubre objeto)' then 'Insumos, instrumental y laboratorio'
 when rama='clinica' and categoria='Insumo clínico' then 'Sin clasificar'
 when rama='clinica' and categoria='Dietético' then 'Dietético clínico'
 when rama='clinica' then 'Sin clasificar'
 when rama='petshop' and nombre ~* '(piedra|arena|pellet|viruta|silica|diatom|bandeja|absorsol|michimix|catway|monkat|gato real|litera|wc cat|pañal|panal|paño|pano|petty clean|placa absorbente|palita|pala |pik-a|granza|toilet)' then 'Arena, litera y sanitarios'
 when rama='petshop' and nombre ~* '(shamp|talco|colonia|perfume|desodorante)' then 'Higiene y cuidado del pelo'
 when rama='petshop' and categoria='Higiene' then 'Higiene petshop - otros'
 when rama='petshop' and nombre ~* '(faja protector|protector post)' then 'Post-quirúrgico y protección'
 when rama='petshop' and nombre ~* 'pouch' and nombre ~* 'gato' then 'Alimento - gato'
 when rama='petshop' and nombre ~* 'pouch' then 'Alimento - perro'
 when rama='petshop' and nombre ~* 'catnip' then 'Juguetes, mordillos y rascadores'
 when rama='petshop' and categoria='Alimento' and nombre ~* '(alfalfa|shulet|carassius|floating|peces|tortuga|canario|cotorra|loro|hamster|conejo|pajaro|semilla|mixtura|alpiste|escamas|chinchilla)' then 'Alimento - otras mascotas'
 when rama='petshop' and nombre ~* '(golocan|galleta|bocadito|snack|premio|bife|stick|treat|grisines|femur|golomiau|orejas|pepas)' then 'Snacks y premios'
 when rama='petshop' and categoria='Alimento' and nombre ~* '(hueso)' then 'Snacks y premios'
 when rama='petshop' and categoria='Alimento' and nombre ~* '(gato|gatito|\mcat\M|catster|catit|kitten|felino|feline|moisty)' then 'Alimento - gato'
 when rama='petshop' and categoria='Alimento' and nombre ~* '(perro|dog|cachorro|canin|puppy|adult|senior|raza|breed|recipe|sobrepeso|v37)' then 'Alimento - perro'
 when rama='petshop' and categoria='Alimento' then 'Sin clasificar'
 when rama='petshop' and categoria='Accesorio' and nombre ~* '(transportador|bolso|mochila|cinturon|caja de transporte|cobertor|fundas para coche)' then 'Transporte y viaje'
 when rama='petshop' and categoria='Accesorio' and nombre ~* '(collar|correa|pretal|arnes|bozal|cadena|ahorque|chapita)' then 'Paseo (collares, correas, pretales)'
 when rama='petshop' and categoria='Accesorio' and nombre ~* '(colchon|clchon|colcho|cucha|siesta|manta|almohad|cama|guata|moises|iglu|casita|antidesgarro)' then 'Camas y descanso'
 when rama='petshop' and categoria='Accesorio' and nombre ~* '(comedero|bebedero|fuente|plato|dispenser|bottle|drink|bowl|duo feed|jumper|mira kc|mamadera)' then 'Comederos y bebederos'
 when rama='petshop' and categoria='Accesorio' and nombre ~* '(pelota|peota|peluche|rascal|chifle|mordillo|juguete|donut|dona|catit|rascador|rascadon|cartocat|soga|hueso|dancer|varita|toy|torpedo|martillo|pompon|cañita|canita|discover|ratita|pluma|pluna|cubo|frisbee|giroscopio|gatito de tela|magic circle|oruga|vertigo|nato|tela-|rama de goma)' then 'Juguetes, mordillos y rascadores'
 when rama='petshop' and categoria='Accesorio' and nombre ~* '(capita|abrigo|buzo|capa|ropa|polar|impermeable|polera|camiseta|chaleco|bandana|zapatilla)' then 'Ropa'
 when rama='petshop' and categoria='Accesorio' and nombre ~* '(calentador|pecera|acuario|colibri|jaula|cage|criceti|cardina|canario|filtro|pajaro|loro|new pet|arco de piedra|rana de|raton|habitrail|hamstera|plantas)' then 'Acuarios, aves y roedores'
 when rama='petshop' and categoria='Accesorio' and nombre ~* '(alicate|cepillo|peine|cortau|corta u|tijera|furminator|manopla|guante magico|dedal|le salon|duchador|adhesive roll)' then 'Peluquería y grooming'
 when rama='petshop' and categoria='Accesorio' and nombre ~* '(kit|llavero|boxpet|puerta|germinador)' then 'Kits y varios'
 else 'Sin clasificar'
end
where subcategoria is null;
